version: "3"

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - PHP_MEMORY_LIMIT=2048M
      - PHP_INI_ALLOW_URL_FOPEN = On
      - PHP_INI_ALLOW_URL_INCLUDE = Off
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
    depends_on:
      - db
      - redis
    networks:
      - app-network

  # MySQL Service
  db:
    image: mariadb:10.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:alpine
    networks:
      - app-network

  # PHPMyAdmin Service (optional)
  phpmyadmin:
    image: linuxserver/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
